apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: elasticsearch-exporter
  name: elasticsearch-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-exporter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: elasticsearch-exporter
    spec:
      containers:
      - command:
        - /bin/elasticsearch_exporter
        - -es.uri=<ELASTICSEARCH_URL> #http://ES_STS_NAME.NAMESPACE.svc.cluster.local:9200
        - -es.all=true
        image: justwatch/elasticsearch_exporter:1.0.2
        imagePullPolicy: IfNotPresent
        name: elasticsearch-exporter
        ports:
        - containerPort: 9108
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 25m
            memory: 64Mi
        securityContext:
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
