apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configuration
  labels:
    app.kubernetes.io/name: prometheus
    name: prometheus-configuration
  namespace: default
data:
  prometheus.yml: |-
    global:
      scrape_interval: 10s
    scrape_configs:
    - job_name: cluster_uuid_cockroachxyz_cockroachdb-app
      metrics_path: '/_status/vars'
      scheme: 'http'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: cockroachidb
        action: keep
      tls_config:
        insecure_skip_verify: true
